/**
 * Page-scoped CSS for `/s` (SPEC-STATIC-PAGES v2 S-2).
 *
 * Split out of `share-page.ts` for the 300-line file ceiling, and it carries no colour: every value
 * is a `var(--token)` reference or a geometry constant, so `theme.ts` remains the only colour source
 * in the repository (P0-3, proven by `tests/edge/83-token-parity.test.ts`).
 *
 * The rules implement the four S-2 surfaces: the sticky 44px brand bar, the tap-to-play overlay that
 * sits on top of the video instead of pushing it down, the horizontal episode rail, and the floating
 * download dock that clears `env(safe-area-inset-bottom)`. The WeChat guidance mask is the last block
 * and is `hidden` in the markup until the script reveals it.
 */

export const SHARE_STYLES = [
  // --- shell: the document scrolls under a sticky brand bar, so the body loses its own padding.
  'body { padding: 0; }',
  '.frame { min-height: 100vh; display: flex; flex-direction: column; }',
  '.shell { padding: var(--space-4); width: 100%; }',
  '.stack > * + * { margin-top: var(--space-4); }',
  '.head > * + * { margin-top: var(--space-2); }',
  // --- brand bar (AC-S2-1): 44px, Lucide `film` + 品牌名, pinned while the visitor scrolls.
  '.bar {',
  '  position: sticky;',
  '  top: 0;',
  '  z-index: 3;',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  gap: var(--space-2);',
  '  min-height: var(--touch-target);',
  '  padding: var(--safe-top) var(--space-4) 0;',
  '  background: var(--surface-overlay);',
  '  border-bottom: 1px solid var(--border);',
  '  -webkit-backdrop-filter: blur(8px);',
  '  backdrop-filter: blur(8px);',
  '}',
  '.bar-brand { display: inline-flex; align-items: center; gap: var(--space-2); color: var(--accent); font-size: var(--text-sm); letter-spacing: var(--tracking-caps); }',
  '.bar-cta {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  min-height: var(--touch-target);',
  '  padding: 0 var(--space-4);',
  '  color: var(--accent);',
  '  font-size: var(--text-sm);',
  '  text-decoration: none;',
  '  border: 1px solid var(--border);',
  '  border-radius: var(--radius-pill);',
  '}',
  '.bar-cta:active { transform: translateY(1px); }',
  // --- stage: the overlay is painted over the poster frame, never beside it.
  '.stage { position: relative; }',
  '.stage > * + * { margin-top: var(--space-3); }',
  '.stage .video + .overlay { margin-top: 0; }',
  '.overlay {',
  '  position: absolute;',
  '  inset: 0;',
  '  display: flex;',
  '  flex-direction: column;',
  '  align-items: center;',
  '  justify-content: center;',
  '  gap: var(--space-2);',
  '  padding: var(--space-4);',
  '  border-radius: 0;',
  '  text-align: center;',
  '}',
  '.tap {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  gap: var(--space-2);',
  '  min-height: var(--touch-target);',
  '  min-width: var(--touch-target);',
  '  padding: var(--space-3) var(--space-5);',
  '  color: var(--accent);',
  '  background: var(--accent-subtle);',
  '  border: 1px solid var(--accent);',
  '  border-radius: var(--radius-pill);',
  '  font-family: inherit;',
  '  font-size: var(--text-base);',
  '  cursor: pointer;',
  '}',
  '.tap:active { transform: translateY(1px); }',
  '.overlay .fineprint { color: var(--fg-2); max-width: var(--container-mobile); }',
  '.state { display: block; }',
  '.state .icon { color: var(--warn); }',
  // --- episode rail (AC-S2-4): a horizontal scroller, current episode marked, others inert.
  '.rail { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius-lg); padding: var(--space-4); }',
  '.rail > * + * { margin-top: var(--space-3); }',
  '.rail-title { font-size: var(--text-base); color: var(--fg); }',
  '.rail-track { display: flex; gap: var(--space-2); overflow-x: auto; padding-bottom: var(--space-2); -webkit-overflow-scrolling: touch; }',
  '.chip {',
  '  flex: none;',
  '  min-height: var(--touch-target);',
  '  padding: 0 var(--space-3);',
  '  color: var(--fg-2);',
  '  background: var(--surface-raised);',
  '  border: 1px solid var(--border);',
  '  border-radius: var(--radius-pill);',
  '  font-family: inherit;',
  '  font-size: var(--text-sm);',
  '  cursor: pointer;',
  '}',
  '.chip.is-current { color: var(--accent-on); background: var(--accent); border-color: var(--accent); }',
  '.rail-hint { color: var(--accent); font-size: var(--text-sm); }',
  // --- panels and calls to action
  '.panel > * + * { margin-top: var(--space-3); }',
  '.panel h2 { font-size: var(--text-md); color: var(--accent); }',
  '.cta-row { display: flex; flex-wrap: wrap; gap: var(--space-2); }',
  '.cta-row > * + * { margin-left: var(--space-2); }',
  '.noscript {',
  '  display: block;',
  '  margin: 0 var(--space-4) var(--space-6);',
  '  padding: var(--space-3) var(--space-4);',
  '  border: 1px solid var(--border);',
  '  border-radius: var(--radius-md);',
  '  color: var(--fg-2);',
  '  font-size: var(--text-sm);',
  '}',
  // --- floating dock (AC-S2-2):常驻 CTA, lifted clear of the home-indicator safe area.
  '.dock {',
  '  position: fixed;',
  '  right: 0;',
  '  bottom: 0;',
  '  left: 0;',
  '  z-index: 3;',
  '  padding: var(--space-3) var(--space-4) calc(var(--space-3) + var(--safe-bottom));',
  '  background: var(--surface-overlay);',
  '  border-top: 1px solid var(--border);',
  '}',
  '.dock .cta { width: 100%; }',
  '.shell { padding-bottom: var(--space-12); }',
  // --- WeChat guidance mask (AC-S2-3): revealed only by a download tap inside that container.
  '.mask {',
  '  position: fixed;',
  '  inset: 0;',
  '  z-index: 5;',
  '  display: flex;',
  '  align-items: flex-start;',
  '  justify-content: flex-end;',
  '  padding: calc(var(--space-6) + var(--safe-top)) var(--space-6) var(--space-6);',
  '  background: var(--surface-overlay);',
  '}',
  '.mask-card {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: var(--space-2);',
  '  max-width: var(--container-mobile);',
  '  padding: var(--space-4);',
  '  background: var(--surface);',
  '  border: 1px solid var(--border);',
  '  border-radius: var(--radius-lg);',
  '}',
  '.mask-card strong { display: inline-flex; align-items: center; gap: var(--space-2); color: var(--accent); font-size: var(--text-base); }',
  '.mask-card .icon { color: var(--accent); }',
  '.mask-close {',
  '  align-self: flex-end;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  min-height: var(--touch-target);',
  '  min-width: var(--touch-target);',
  '  color: var(--fg-2);',
  '  background: transparent;',
  '  border: 0;',
  '  cursor: pointer;',
  '}',
  // The dock would otherwise cover the last panel on a short viewport.
  '@media (min-width: 720px) {',
  '  .dock { position: static; border-top: 0; }',
  '  .shell { padding-bottom: var(--space-6); }',
  '}'
].join('\n');
